/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    news: News;
    schedule: Schedule;
    media: Media;
    users: User;
  };
  globals: {};
}

export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}

export interface News {
  id: string;
  title: string;
  content: {
    [k: string]: unknown;
  }[];
  coverImage?: string | Media | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface Schedule {
  id: string;
  day: 'Maandag' | 'Dinsdag' | 'Woensdag' | 'Donderdag' | 'Vrijdag' | 'Zaterdag' | 'Zondag';
  groupName: string;
  startTime: string;
  endTime: string;
  instructor?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}